spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 200000000
      max-request-size: 200000000

---
spring:
  profiles: local
  data:
    cassandra:
      keyspace-name: test
      schema-action: create_if_not_exists
      contact-points: localhost

---
spring:
  profiles: docker
  data:
    cassandra:
      keyspace-name: test
      schema-action: recreate
      contact-points: cassandra
logging:
  level:
    com.datastax.driver: ERROR

