spring:
  profiles:
    active: local

---
spring:
  profiles: local
  data:
    cassandra:
      keyspace-name: player_session
      schema-action: recreate
      contact-points: localhost

---
spring:
  profiles: docker
  data:
    cassandra:
      keyspace-name: player_session
      schema-action: recreate
      contact-points: cassandra
