version: "3"

services:
  app:
    image: player-session-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
    - cassandra
    ports:
      - "8080:8080"
    links:
      - cassandra
    networks:
      - test
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  cassandra:
    image: cassandra
    volumes:
    - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    ports:
      - '7000:7000'
      - '9042:9042'
    networks:
      - test

networks:
  test:
    driver: "bridge"